CurriculumViewer/Controllers/ExamProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CurriculumViewer.Abstract.Services;
using CurriculumViewer.ApplicationServices.Abstract.Services;
using CurriculumViewer.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CurriculumViewer.WebUI.Controllers
{
    [Authorize]
    public class ExamProgramController : Controller
    {
        public IGenericService<ExamProgram> examProgramService;
        public ExamProgramController(IGenericService<ExamProgram> ExamProgramService)
        {
            this.examProgramService = ExamProgramService;
        }

        // GET: ExamProgram
        public ActionResult Index()
        {
            return View(this.examProgramService.FindAll());
        }

        // GET: ExamProgram/Details/5
        public IActionResult Details(int id)
        {
            return View(examProgramService.FindById(id, new string[] { "Courses" }));
        }

        // GET: ExamProgram/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ExamProgram examProgram)
        {
            IActionResult actionResult = View(examProgram);
            
            if (!ModelState.IsValid)
            {
                actionResult = View("Error");
            }
            else if (examProgramService.Insert(examProgram) == 1)
            {
                actionResult = RedirectToAction(nameof(Index));
            }

            return actionResult;
        }
        

        // GET: ExamProgram/Edit/5
        public ActionResult Edit(int id)
        {
            return View(examProgramService.FindById(id));
        }

        // POST: ExamProgram/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ExamProgram examProgram)
        {
            IActionResult actionResult = View(examProgram);

            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values;
                actionResult = View("Error");
            }
            else if (examProgramService.Update(examProgram) == 1)
            {
                actionResult = RedirectToAction(nameof(Index));
            }

            return actionResult;
        }
        
        // POST: ExamProgram/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            ExamProgram examProgram = examProgramService.FindById(id);
            IActionResult actionResult = View();

            if (examProgramService.Delete(examProgram) == 1)
            {
                actionResult = RedirectToAction(nameof(Index));
            }

            return actionResult;
        }
    }
}

CurriculumViewer/Views/ExamProgram/Create.cshtml
@model ExamProgram
@{
    ViewData["Title"] = "Examenprogramma aanmaken";
}

@await Component.InvokeAsync(ViewComponentConstants.BreadCrumbs)

<div class="row">
    <div class="col s12">
        <h2>@ViewData["Title"]</h2>
    </div>
</div>
<div class="row">
    <div class="col s12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="input-field col s6">
                    <label asp-for="StartDate"></label>
                    <input asp-for="StartDate" type="text" class="datepicker datepicker-examprogram" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="input-field col s6">
                    <label asp-for="EndDate"></label>
                    <input asp-for="EndDate" type="text" class="datepicker datepicker-examprogram" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>
            <div class="input-field">
                <input type="submit" value="Opslaan" class="btn" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Terug naar lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync(PartialConstants.ValidationScripts);}
}

CurriculumViewer/Views/ExamProgram/Details.cshtml
@model ExamProgram

@{
	ViewData["Title"] = "Details";
}
@await Component.InvokeAsync(ViewComponentConstants.BreadCrumbs, new { objectName = Model.Name, ObjectId = Model.Id })

<div class="row">
	<div class="col s12">
		<h2>Examenprogramma @Model.Name</h2>
	</div>
</div>

<div class="row">
	<div class="col s6 details-main">
		<h3>Programmaonderdelen:</h3>
		@await Component.InvokeAsync(ViewComponentConstants.List, new { data = Model.Courses.OrderBy(e => e.Name), expression = ListComponentFieldTypes.Name })
	</div>
</div>

@await Html.PartialAsync(PartialConstants.DetailActions, Model)

CurriculumViewer/Views/ExamProgram/Edit.cshtml
@model ExamProgram
@{
    ViewData["Title"] = "Examenprogramma aanpassen";
}

@await Component.InvokeAsync(ViewComponentConstants.BreadCrumbs)

<div class="row">
    <div class="col s12">
        <h2>@ViewData["Title"]</h2>
    </div>
</div>
<div class="row">
    <div class="col s12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="input-field col s6">
                    <label asp-for="StartDate"></label>
                    <input asp-for="StartDate" type="text" class="datepicker" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="input-field col s6">
                    <label asp-for="EndDate"></label>
                    <input asp-for="EndDate" type="text" class="datepicker" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>
            <div class="input-field">
                <input type="submit" value="Wijzigen" class="btn" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Terug naar lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync(PartialConstants.ValidationScripts);}
}

CurriculumViewer/Views/ExamProgram/Index.cshtml
@model IEnumerable<ExamProgram>

@{
	ViewData["Title"] = "Index";
}

@await Component.InvokeAsync(ViewComponentConstants.BreadCrumbs)

<div class="row">
	<div class="col s12">
		<h2>Examenprogramma's</h2>
		@await Html.PartialAsync("_CreateButton", "Examenprogramma")
		<app-data-table data-records='@Html.Raw(Json.Serialize(Model.ToList()))'
						data-limit="10"
						data-columns="name:Examenprogramma"
						data-url_details="@Url.Action("details", "ExamProgram", null)" />
	</div>
</div>